### ISSUE TITLE
Unify snippets in one module?

### ISSUE THREAD

**Issue by yajo** [OCA/website#108]
I launched https://github.com/OCA/website/pull/107, but will have to launch more probably.

Should OCA unify all snippets in one module (i.e. website_snippets_extra), or make one for each one?

**Comment by rafaelbn** [comment]
I agree :+1:

**Comment by pedrobaeza** [comment]
Each snippet should be in a separate module. The maintenance will be better. Imagine a mega-module with all snippets that you have to migrate to a newer version. It's all or nothing. It also helps to locate the involved code in a snippet if you have a problem in it.

**Comment by rvalyi** [comment]
I agree with @pedrobaeza.
Also I strongly advise against using Odoo for web dev because I bet it will be a dead end or at least something you will not be able to capitalize on, but that's only my own opinion here. Sustainable alternatives are coming stay tuned.

**Comment by rafaelbn** [comment]
OK, if I imagine that we have 20 snippets, this will be complicated.

I didn't think it well, @Yajo if we put all together we cannot put each one in the correct repo. Maybe the idea for themes is correct but same approach in OCA will be difficult.

**Comment by rafaelbn** [comment]
> Sustainable alternatives are coming stay tuned

@rvalyi could you give us some more info or concepts? thanks

**Comment by yajo** [comment]
OK thanks, then I'll continue as until now.

**Comment by lisandi** [comment]
The points rvalyi are the most important IMHO - continuing it will be a dead end approach, but putting all those snippets into its own module will blow up the code minimal but give much more freedom to localise problems - you could very easy install and deinstall a module and check the output in the front-end. beside that those single snippet modules could be individually put into a specific site which means you could even charge customers for the amount of snippets.
Most important would be actually that all those snippets are kept AGPL v.3 or even GPL v.3 as both can be combined and both can't be used in proprietary products which seems to be the final goal after all those license changes. Keep your freedom and your job by not applying the LGPLv.3 to your modules! Even your module is GPL or AGPL v.3 it can be linked to LGPL v.3 but not to a product which is proprietary and you won't have access to the code itself!

I really recommend that OCA will open up there own THEME Sales website and a separated one where all those Snippet modules could be bought. Use the money you can earn by setting up a shop on OCA to finance further development or even the conversion to python 3 etc. It would be good if OCA would stand more and more on their own stable foundation.

+1 ro rafaelbn request @rvalyi to tell a bit more about his approach and concept, as than probably we could do things much better in the same direction instead of reinventing and duplicating wheels.

**Comment by rvalyi** [comment]
@lisandi @rafaelbn
Akretion will start building a full blown open source e-commerce based on LocomotiveCMS and using Odoo live objects via erpify or their Solr cache via solarize all that inside the Liquid templating language. That is bridging Odoo for the backend, LocomotiveCMS and Shopify technologies with the minimum amount of code, all standing on the Rails giant (you know the guy powering that Github thing your are reading this right now).

Note that unlike with Magento or Prestashop connectors, data is NOT duplicated so it costs much less to implement and maintain. It's just that optionally if you want alien scalability and security, your public catalog can optionally be backed by an Apache Solr cache. But since its just denormalized noSQL, there is no data integrity issue and this is trivial integration.
This is not a dream, this technology has been in production more than 1 year now via Odoo v7 on that website for instance:
http://guarulhos.zupy.com.br/?utf8=%E2%9C%93&q=academia
http://guarulhos.zupy.com.br/imoveis
(also see http://franquias.zupy.com.br )

I hope I'll be able to blog about the plan this week end, I'll let you know.

**Comment by max3903** [comment]
I don't mind having them all in one module, but anyone should be able to configure any possible combinations.

**Comment by lisandi** [comment]
That would be also a possibility

something like checkboxes to choose from individually for each customer.
But that would actually be the same like installing them via the
module/apps manager

Also customers could enable any snippet afterwards very easily themselves
and your earnings would be gone ;-)

If those are separrate snippets they would need to install them themselves
at least which is a bit more work to do than only clicky clack and it is
there.

Customer friendly is a one module solution with a snippet chooser - that is
true. But it has to be AGPL!!! that is very important! like mentioned
before.

ANDI BECKER

**Comment by yajo** [comment]
You choose snippets by dragging them, what you say is some extra work for no extra benefit. If you want to choose which snippets to add, then we put 1 snippet per module and you install those you want.

**Comment by treviser** [comment]
FYI: Covering all 25 themes available so far, we have about 90 snippets/building blocks available in Odoo Website Themes.

**Comment by lisandi** [comment]
@Yajo
This is what I prefer the most as this would be also the best option to add
new snippets by the community, test snippets separately on a one by one
base, and the "integrator" can choose what he wants to put available for
the customer or not.
All snippets could actually be installed into a separate custom_snippet (a
usual odoo-addon) folder and added to the addons paths, so it is much
easier to be maintained as in one single module and the functionality of
selecting a snippet or not is already build in in odoo, so no worries here
to.

This option also would be the one which could bring people to contribute
their new snippets and to maintain their former ones which are already in
the repository on OCA.

@Ermin Great!

For the themes also put them in a separate repository i.e. custom_themes (a
usual addons_path) from the snippets so that it does not get mixed up and
you can maintain a very clear structure inside your odoo installation but
also in the repositories on OCA.

With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,

<html><div>

</div><div> _ANDI BECKER_

CEO/General Manager LisAndi Co., Ltd.

_about.me/andibecker
http://about.me/andibecker</div></html>--------------------------------------------------_
_LisAndi Co. Ltd._, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Mobile: +66 (0)81 606 3378
VoIP:   +49 (0)711 50 88788 50
Fax:     +49 (0)711 50 88788 50
Skype:          lisandi
Facebook:     andibecker
Google Talk/Facetime/eMail:  andi@lisandi.com

---

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorized copying, disclosure or distribution of the material in this
email is strictly prohibited. Email transmission security and error-free
status cannot be guaranteed as information could be intercepted, corrupted,
destroyed, delayed, incomplete, or contain viruses. The sender therefore
does not accept liability for any errors or omissions in the contents of
this message which may arise as a result of email transmission
