### ISSUE TITLE
Website with permissions

### ISSUE THREAD

**Issue by kkoci** [OCA/website#325]
Hi

Is there a module on this repo, which can render products or webpages according to the user logged in into the ecommerce?

Or something similar to this?

Best Regards

**Comment by simahawk** [comment]
Hi,

what do you mean precisely?

You can use `groups` attribute on html elements too.

Note that if you use `group_portal` you cannot catch anonymous users since
the anonymous user is actually an odoo fake user.

To catch anon users use an IF block like `<t t-if="request.session.uid">`.

Anyway, it depends on what you are trying to achieve, so maybe you don't
need a std module but just a small customization.

Cheers,

**Comment by kkoci** [comment]
Thank You very much!

Awesome

**Comment by lasley** [comment]
Closing - this looks solved
