### ISSUE TITLE
Unable to install module  "website_multi_theme". Unable to find 'sass' in path

### ISSUE THREAD

**Issue by lgarcia11** [OCA/website#426]
Error received when trying to install.
Unable to install module "website_multi_theme" because an external dependency is not met: Unable to find 'sass' in path

**Comment by yajo** [comment]
Then install sass and retry

**Comment by thopy** [comment]
I have exactly the same problem as @Igarcia11, additionally I installed sass (what was really a hassle on win7 because compiling the c source is not easy for me) and tested it successfully on the python command line but odoo refuses to recognize that it is there and still returns an error message noting that there is a dependence on sass and it seems to be not installed. 

I know this issue is closed and probably nobody will reply and my problem is even offtopic because my question is rather why odoo does not recognize the sass installation but maybe someone of you can give me a hint. 

I am using python 3.5, odoo 11.0 source install and working with eclipse. 

I found also this thread 
[https://www.odoo.com/de_DE/forum/hilfe-1/question/how-to-install-python-modules-on-windows-for-odoo-96101](https://www.odoo.com/de_DE/forum/hilfe-1/question/how-to-install-python-modules-on-windows-for-odoo-96101)
which seems to point to the same problem. But nobody really answered there.

**Comment by pedrobaeza** [comment]
But that's not something of the module, but your decision of installing Odoo on Windows. Every documentation you can read advises you not to install this on Windows because the installation of anything there is a total pain. Use a Linux VM if you don't want to have a complete Linux system.
