### ISSUE TITLE
website_addthis: sharing buttons titles included in SEO optimization title

### ISSUE THREAD

**Issue by alexdhika** [OCA/website#493]
Edit SEO Title Error (repeat title) when activate Addthis Integration

Odoo v11

**Comment by pedrobaeza** [comment]
Which error? Which module? With this information, we can't hardly help you.

**Comment by alexdhika** [comment]
Module "AddThis integration"
Error = Repeat Title when edit SEO meta in website blog post

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem, please.

**Comment by alexdhika** [comment]
like this
https://image.ibb.co/j3sT1y/addthis.png

**Comment by alexdhika** [comment]
"AddThis integration" add some repeated title when i edit meta seo

**Comment by pedrobaeza** [comment]
@simahawk can you check this, please?

**Comment by alexdhika** [comment]
@pedrobaeza thanks :)

**Comment by simahawk** [comment]
I'll check in a while

**Comment by simahawk** [comment]
not an issue on addon side:
1. AddThis adds sharing buttons including (don't know why) `<title />` elements:
![image](https://user-images.githubusercontent.com/347149/42992437-cc8834e8-8c08-11e8-8645-f98ee39b208a.png)
2. Odoo [seo.js selects `title` instead of `head title`](https://github.com/odoo/odoo/blob/47b376e66d2e9f303934a18800070bdb48d472d0/addons/website/static/src/js/menu/seo.js#L243) and catches them all

Having titles outside HEAD is wrong by spec https://www.w3.org/TR/html401/struct/global.html#h-7.4.2 so: either you customize your sharing templates or you complain w/ AddThis :)

**Comment by alexdhika** [comment]
But if i disabled addthis integration no error found
