### ISSUE TITLE
[11.0][website_js_below_the_fold] Possible inconsistent behavior between power user and normal user

### ISSUE THREAD

**Issue by simahawk** [OCA/website#512]
[Here ](https://github.com/OCA/website/blob/11.0/website_js_below_the_fold/templates/website_js_below_the_fold.xml#L24
) we move JS only if we are not power users.

I've struggled for some time because for power users my JS was working smoothly and for simple users it did not.

The issue was actually that I have a custom template where I was temporarely loading some minor JS straight into HEAD w/ `<t t-set="head" />` (not really a good idea anyway).

We might face this issue in other ways and all in all moving the JS is for a good perf reason... 
@tarteo do you have an answer? Thanks in advance! :)

**Comment by tarteo** [comment]
I think the issue is that the piece of JS you used is dependent on something that is loaded in the assets bundles. E.g. website_analytics_piwik works fine with the Javascript on the bottom (not sure if this is because it also puts it on the bottom).
But I see the problem in having to test that kind of Javascript twice (once with power and once without).
If we change the module to always load the Javascript on the bottom we first have to test if the editor doesn't break. But generally the JS should be in the assets bundles :)

**Comment by simahawk** [comment]
@tarteo that's my point! :) The question is: did you have issues w/ the editor w/ resources moved below?
All in all I don't see a reason - but this - to not make editors' experience faster, no?

**Comment by tarteo** [comment]
@simahawk I think i had problems with the editor, but I can't really remember anymore :(

**Comment by simahawk** [comment]
hehe, ok, I'll try when I have time. Thanks for your feedback anyway!
