### ISSUE TITLE
[8.0] Broken build on phantomjs-related tests

### ISSUE THREAD

**Issue by simahawk** [OCA/website#523]
https://travis-ci.org/OCA/website/jobs/436459091#L1783

Seems because of timeouts.

@Yajo @hbrunn @moylop260 anyone already dealing with this?

**Comment by moylop260** [comment]
Is not related with the error above: 
https://travis-ci.org/OCA/website/jobs/436459091#L1601

`2018-10-03 03:52:35,129 4654 ERROR openerp_test openerp.sql_db: bad query: UPDATE "website_seo_redirection" SET "destination"='/c',"write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (50)`

https://travis-ci.org/OCA/website/jobs/436459091#L1582
`2018-10-03 03:52:35,019 4654 ERROR openerp_test openerp.sql_db: bad query: INSERT INTO "website_seo_redirection" ("id", "origin", "destination", "relocate_controller", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('website_seo_redirection_id_seq'), '/same-url', '/same-url', true, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id`

**Comment by yajo** [comment]
@moylop260 that failure is an expected failure. Logs should have been muted to avoid distraction, but just check that the test that triggers the failure is testing a SQL constraint.

@simahawk indeed it seems like it cannot find the tour. One possibility is that there's some syntax error because somebody introduced a ES6 syntax that PhantomJS cannot understand. Another option is that the admin is not able to load editor assets. Not sure, it can be many things.

Maybe just moving the tour file to public assets and browsing with the public user can fix the branch. Otherwise, I would approve a PR that just removes that test. I personally don't maintain it anymore in v8, so I care more about the "green" that the tour itself. :roll_eyes:

**Comment by moylop260** [comment]
I just ran the tour login with admin from the runbot's build and the issue is reproduced (I think so):

 - ![tour](https://user-images.githubusercontent.com/6644187/46660475-65130880-cbb7-11e8-892a-d16e4add4ecd.gif)

**Comment by yajo** [comment]
Oh, why does it go to the backend? The tour is expected to run in website... :roll_eyes:
