### ISSUE TITLE
[11.0] Internal Server Error for runbot Website Snippet Presets

### ISSUE THREAD

**Issue by JulienMartinez** [OCA/website#984]
Hi, @sbidoul 

I am looking to use the runbot from the "Website Snippet Presets" module to do tests and possibly port it to v16, 
however this no longer works and returns an "Internal Server Error".

Cordially

**Comment by sbidoul** [comment]
Indeed, if you are looking at runboat for website 11.0, this build does not start: https://runboat.odoo-community.org/builds?repo=oca/website&target_branch=11.0

If you look at the init log it says `Unable to install module "website_multi_theme" because an external dependency is not met: Unable to find \'sass\' in path`.

The solution would be to update the manifest of website_multi_theme to add a `deb` external dependency with the list of ubuntu packages to install.
